//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wearhouse
{
    using System;
    using System.Collections.Generic;
    
    public partial class lot
    {
        public int lot_id { get; set; }
        public int product_id { get; set; }
        public int supplier_id { get; set; }
        public System.DateTime lot_receive_date { get; set; }
        public Nullable<int> lot_receive_qty { get; set; }
        public decimal lot_unit_cost { get; set; }
        public Nullable<decimal> lot_total_cost { get; set; }
        public Nullable<System.DateTime> lot_expire_date { get; set; }
        public byte[] lot_create_at { get; set; }
        public Nullable<int> lot_balance_qty { get; set; }
    
        public virtual product product { get; set; }
        public virtual supplier supplier { get; set; }
    }
}
