
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Wearhouse
{

using System;
    using System.Collections.Generic;
    
public partial class product
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public product()
    {

        this.lot = new HashSet<lot>();

        this.transaction = new HashSet<transaction>();

    }


    public int product_id { get; set; }

    public string product_name { get; set; }

    public int producttype_id { get; set; }

    public byte[] product_image { get; set; }

    public string product_unit { get; set; }

    public Nullable<decimal> product_unitprice { get; set; }

    public Nullable<int> product_stock_qty { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<lot> lot { get; set; }

    public virtual producttype producttype { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<transaction> transaction { get; set; }

}

}
