
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Wearhouse
{

using System;
    using System.Collections.Generic;
    
public partial class transaction
{

    public int trans_id { get; set; }

    public int product_id { get; set; }

    public System.DateTime trans_date_time { get; set; }

    public int trans_type { get; set; }

    public string trans_reason { get; set; }

    public Nullable<int> trans_qty { get; set; }

    public Nullable<decimal> trans_unit_price { get; set; }

    public Nullable<decimal> trans_total_amount { get; set; }

    public Nullable<int> supplier_id { get; set; }



    public virtual product product { get; set; }

    public virtual supplier supplier { get; set; }

}

}
