

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Wearhouse
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class wearhouseEntities : DbContext
{
    public wearhouseEntities()
        : base("name=wearhouseEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<lot> lot { get; set; }

    public virtual DbSet<product> product { get; set; }

    public virtual DbSet<producttype> producttype { get; set; }

    public virtual DbSet<supplier> supplier { get; set; }

    public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }

    public virtual DbSet<transaction> transaction { get; set; }

    public virtual DbSet<verify_question> verify_question { get; set; }

    public virtual DbSet<userPass> userPass { get; set; }

}

}

